my_blog/blog/urls.py
#coding: utf:8
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^post/(\d+)/$', views.posted, name="posted"),
        url(r'^tag/(\w+)/$',views.tag, name="taged"),
        url(r"^add_comment/(\d+)/$", views.add_comment, name="add_comment"),

        )

my_blog/my_blog/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my_blog.views.home', name='home'),
    # url(r'^my_blog/', include('my_blog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    )

my_blog/blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=200)


    def __unicode__(self):
        return self.title

    def get_tags(self):
        tgs = self.tags.split()
        return tgs
        
    
class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    body = models.TextField()
    post = models.ForeignKey(Post)

   

    def __unicode__(self):
        return unicode("%s: %s" % (self.post, self.body[:60]))

my_blog/blog/forms.py
from django import forms
from blog.models import Comment, Post

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea)
    author = forms.CharField(max_length=60, required=False)
    
    
    class Meta:
        
        model = Comment
        exclude = ['post']

    def clean_author(self):

        return self.cleaned_data.get('author') or "Anonymous"
        
       


        

my_blog/blog/views.py
#coding:utf-8


from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from blog.models import Post, Comment 
from blog.forms import CommentForm


def posted(request, post_id):
    context_dict = {}
    context = RequestContext(request,{"all_tags":make_tags()})
    pst = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=pst)
    context_dict["post"] = pst
    context_dict["comments"] = comments
    context_dict["form"] =  CommentForm()
    return render_to_response('blog/post.html', context_dict, context)


def index(request): 
    context = RequestContext(request, {"all_tags":make_tags()})
    post_list = Post.objects.all()[:10]
    len_comments(post_list)
    return render_to_response('blog/index.html',{"post_list":post_list}, context)

def tag(request, t):
    context_dict = {}
    context = RequestContext(request,{"all_tags":make_tags()})
    posts_with_tag = Post.objects.filter(tags__icontains=t)
    len_comments(posts_with_tag)
    context_dict["tag"] = t
    context_dict["post_list"] = posts_with_tag 
    return render_to_response('blog/tags.html', context_dict, context)

#helper function
def make_tags():
    posts = Post.objects.all()
    posts = (p.get_tags() for p in posts)
    posts = sum(posts, [])
    tag_list = []
    [tag_list.append(c) for c in posts if c not in tag_list]
    return tag_list

#helper function
def len_comments(post_list):
    for p in post_list:
        p.len_comments = len(Comment.objects.filter(post=p))
    

def add_comment(request, pk):
    
    post=Post.objects.get(pk=pk)
    if request.method == "POST":
        context = RequestContext(request,{"all_tags":make_tags()})
        comment = Comment(post=post)
        comment = CommentForm(request.POST, instance=comment)
        if comment.is_valid():
            comment.save()
        else:
            form = CommentForm()
            comments = Comment.objects.filter(post=post)
            return render_to_response('blog/post.html',{"post":post,"comments":comments,
                                                        "error":comment.errors, "form":form },
                                      context)
       
            
    return HttpResponseRedirect("/blog/post/%s" % pk)
            
        

my_blog/templates/blog/base.html
<!DOCTYPE html>

<html>
    <head>
        <title>{% block title %}My Blog{% endblock %}</title>
    </head>

    <body>
        <div  id="container">
	  <h4><a href="{% url 'blog:index'  %}">Home</a></h4>
	  <div style="width: 70%; float:left" id="posts">{% block post_body %}{% endblock %}</div>
	  <aside style="width: 20%;float:right; border: solid black 1px">
	  <h1 style="text-align:center">Tags:</h1>
	  <ul>
	    {% for tag in all_tags %}
	    <li> <a href="{% url 'blog:taged'  tag  %}">{{ tag }}</a></li>
	    {% endfor %}
	    
	  </ul>
	  </aside>
	</div>
	
    </body>
</html>

my_blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load url from future %}


{% block post_body %}
{% block tags %}{% endblock %}
<div class='main'>

<ul>
   {% for post in post_list %}
   <div class="title">
     <h3><a href="{% url 'blog:posted'  post.id  %}">{{ post.title }}</a></h3>
   </div>
   <ul>
     <div class="time">{{ post.created }}</div>
     <div class="body">{{ post.body|linebreaks }}</div>
     <div class ="tags">
       <p> Tags: 
       {% for tag in post.get_tags %}
	 <a href="{% url 'blog:taged'  tag  %}">{{ tag }}</a>
	 {% if not forloop.last %}
	 |
	 {% endif %}
	 
	   {% endfor %} </p>
       <p> Comments: {{post.len_comments}} </p>
       

       
     </div>
   </ul>
   {% empty %}
   <p> Нет постов </p>
   {% endfor %}
</ul>

</div>





{% endblock %}

my_blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block post_body %}
<div class="title">
  <h1>{{ post.title }}</h1>
</div>
<ul>
    <div class="time">{{ post.created }}</div>
    <div class="body">{{ post.body|linebreaks }}</div>
    <div class ="tags">
       <p> Tags: 
       {% for tag in post.get_tags %}
	 <a href="{% url 'blog:taged'  tag  %}">{{ tag }}</a>
	 {% if not forloop.last %}
	 |
	 {% endif %}
	   {% endfor %} </p>
       


     </div>
</ul>


<!-- Comments  -->
{% if comments %}
    <p>Comments:</p>
{% endif %}

{% for comment in comments %}
    <div class="comment">
        <div class="time">{{ comment.created }} | {{ comment.author }}</div>
        <div class="body">{{ comment.body|linebreaks }}</div>
    </div>
{% endfor %}

<div id="addc">Add a comment</div>

   {% if error %}
    <p> {{error}}</p>
  {% endif %}
<!-- Comment form  -->
<form action="{% url 'blog:add_comment' post.id %}" method="POST">{% csrf_token %}
    
       {{form.as_p}}
    <div id="submit"><input type="submit" value="Submit"></div>
</form>



{% endblock %}

my_blog/templates/blog/tags.html
{% extends 'blog/index.html' %}

{% block tags %}
<h4>Tag: {{tag}}</h4>

{% endblock %}